### ISSUE TITLE
Implement class_registry

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#11]
Classes will be registered in the class_registry.index file when created. 
This will allow selection of existing classes from menu, test for existing classname in new class creation without repeated iteration over filesystem.

https://github.com/toonarmycaptain/dionysus/blob/5c95693e4dfa4c1a12308684281532f3ee7089f5/dionysus_app/class_functions.py#L135

On startup: 
- Check for registry and check registry for consistency with data/update if incomplete/has entries without data in app setup logic of  app_main.py:https://github.com/toonarmycaptain/dionysus/blob/5c95693e4dfa4c1a12308684281532f3ee7089f5/app_main.py#L28
[pathlib.iterdir](https://docs.python.org/3.4/library/pathlib.html#basic-use) will be particularly useful for this, and much less verbose than the os alternative. #10 
- Cache registry in as Python dict for ease of searching.

Modify:
- Add classlist updates this dict AND registry file on disk
- Modify classlist updates this dict AND registry file on disk

**Comment by toonarmycaptain** [comment]
Are you working on this @stoff3l?

**Comment by stoff3l** [comment]
Hi, I was sick for a bit and started looking at it this weekend. I however don't have as much time as I thought I'd have so it might actually be better if someone else picks this one up? Apologies

**Comment by toonarmycaptain** [comment]
No problem. You ok?
