### ISSUE TITLE
Logic for image generation

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#17]
Taking a class list/avatars and data set with graph parameters (scale/bar widths, axis etc) and plotting the avatars. 
Plan is to use matplotlib eg [this](https://stackoverflow.com/questions/22566284/matplotlib-how-to-plot-images-instead-of-points) and [this](https://stackoverflow.com/questions/4860417/placing-custom-images-in-a-plot-window-as-custom-data-markers-or-to-annotate-t)

The idea is to create essentially a bar graph, with with similar scores are stacked on top of eachother in columns - the specifics would be an option in the graph creation logic #16.
This is the rough avatar arrangement I'm imagining*: 
![Image from http://www.mathblaster.com/coolmath/articles/reading-bar-graphs](http://m.mathblaster.com/Mathblaster/CoolMath/Article-Images/reading-bar-graphs.jpg)
So create a graph, iterate over the students/avatars/scores and plot the avatars. Save the image.

*Borrowed from [mathblaster.com](http://www.mathblaster.com/coolmath/articles/reading-bar-graphs).

**Comment by toonarmycaptain** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/toonarmycaptain/dionysus/issues/15 (Edit class dialogue and logic), and https://github.com/toonarmycaptain/dionysus/issues/16 (Graph creation logic/dialogue).

**Comment by WrightKD** [comment]
I can help with this.

**Comment by toonarmycaptain** [comment]
Welcome. Sounds great, and thankyou!

**Comment by WrightKD** [comment]
This is what I have so far. Is it what you want? 
![image](https://user-images.githubusercontent.com/43699191/46565419-7a660980-c90f-11e8-9167-dade930fb5c9.png)

**Comment by toonarmycaptain** [comment]
Looks good to me. Can it take unique avatars? We don't need the grid behind it, and will mess with the axis, but that's all configurable detail. 
My goal is a working prototype, then prettifying it, adding features to supply avatars rather than cleaning and sizing images by hand first (far simpler than automated image rocessing/manipulation, of which I have zero expertise).

**Comment by WrightKD** [comment]
You can add any image , which for some other reason has to be a .png image , as the avatar. I'm still trying to figure out how to get the axis values correct (I'm also not sure if it must just be a scale from 1 - 10 or what do you need it to be). I do think that resizing the images by hand will be a pain for the user and I think it will not be that difficult to resize an image within the application.
btw I did get a package that converts all given images to .png so that won't be a problem.

**Comment by toonarmycaptain** [comment]
PIL should be able to convert images. As for scaling I figure the default would be 0-100% on the x axis, with columns set for 0-9, 10-19...80-89, 90-100, but I also expect to custom scale (eg for a quiz that is out of 15). 

There might be an advantage in keeping everything png rather than jpeg, since according to [this SO question(https://stackoverflow.com/questions/46013594/matplotlib-reads-jpg-into-int8-and-png-into-normalized-float) matplotlib does png natively but drops into python for jpg. So converting to png when accepting images, then processing in png (and outputting as jpg only if needed) might be a more efficient and straightforward plan than working with jpgs.

**Comment by toonarmycaptain** [comment]
How's this going? Can you tell me anything about the interface so I can work on #16 the code for taking data and calling the image creator?

**Comment by toonarmycaptain** [comment]
@WrightKD if you're no longer working on this, can you commit what you have, and I'll take it form there?
