### ISSUE TITLE
Fix appveyor.yml

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#19]
Primary users will be Windows users. Appveyor.yml is not set up properly yet. 

*Preferably test on Python 3.7, but if not available, 3.6 should be sufficient, although plan is to package with a Python 3.7 virtualenv interpreter.

*32 and 64 bit implementations also needed.

**Comment by toonarmycaptain** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/toonarmycaptain/dionysus/issues/5 (Fix 'Relative import 'dionysus_app.main_menu', should be '_master.dionysus_app.main_menu'' issue in app_main.py).

**Comment by mbarakaja** [comment]
Hello, I have forked this repo and setup Appveyor. The problem is that the one of the test cases fails. Do you want that fixed in the same pull request?

**Comment by mbarakaja** [comment]
You should use pathlib to make your project more OS agnostic.

**Comment by toonarmycaptain** [comment]
Sure. Which test case is failing? I thought we switched everything to use pathlib in #10?

**Comment by toonarmycaptain** [comment]
Thankyou so much for contributing, by the way. Can you include 32 bit support also?

**Comment by mbarakaja** [comment]
Well, let finish AppVeyor setup first and then we can see what can be improved on pathlib usage.
