### ISSUE TITLE
Convert `class_data` to dict and store as JSON

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#25]
Currently format for .cld class data file is:
```
f'{student_name}, {avatar_filename}\n' for every student in the class. 
```
Which is bad because it has to be unnecessarily processed when reloaded. JSON would seem to be a much better and less error-prone solution (open to advice).
Saving as a JSON'd dict means we can directly de-JSON the dict and use it. 
Pass that dict to the score-entry logic, add the scores (or `None`) for each student, pass to the image generation. 
Nice and simple. 

Using the student name as a key, the uncleaned input/real name, and the filename of the student's avatar:
```
class_data = { 
    'student_name_1': ['student 1 real name', 'student1_avatar_file_name'],
    'student_name_2': ['student 2 real name', 'student2_avatar_file_name'],
    'student_name_3': ['student 3 real name', 'student3_avatar_file_name'],
    'student_name_4': ['student 4 real name', 'student3_avatar_file_name'],
    'student_name_5': ['student 5 real name', 'student3_avatar_file_name'],
    'student_name_6': ['student 6 real name', 'student3_avatar_file_name'],
    }
```
I think the class name should be within the file (probably the first line), a JSON'd dictionary of the class data should be the second line.

* Refactor `create_classlist_data`
Function `create_classlist_data` in [class_functions](https://github.com/toonarmycaptain/dionysus/blob/master/dionysus_app/class_functions.py) will need to be refactored, which is nice, because it's a little ugly anyway.

Factor out the taking of class data into a function. 
Factor out the file write. 
* Tests
We'll need test asserting the dict JSON'd and written to disc is the same as that loaded and de-JSON'd. 
A test with dummy data asserting that the data in is the same as the data reloaded from disc would be nice too, although I've never worked out how to test a while loop well.

**Comment by schedutron** [comment]
Can I work on this please?

**Comment by toonarmycaptain** [comment]
Welcome! Sure.

**Comment by toonarmycaptain** [comment]
There are no CI tests yet, the code for editing/reviewing a class hasn't been written, nor the image generation code which would use the data. The best I can suggest is verifying that the class list creation code works to create the class-data file without error (data in .cld file makes sense, any avatars you supplied are in appropriate folder with correct name, attempting to create a second class with the same name tells you you already have one with that name), and a maual double check that running `json.load` on the saved data returns the saved dict intact without error and containing the expected data. 

Feel free to submit any tests you write as well, or any code you write to test manually as a comment that someone else could use to write the formal tests. I'm quickly learning that good tests are both critical when working with others on a shared project, and much, much easier to write when first drafting code, than trying to come back and write as an afterthought!

**Comment by toonarmycaptain** [comment]
Does this look good to you? Shall I merge it, or did you want to do some more, eg tests?

**Comment by schedutron** [comment]
Sorry got a bit late. I need to think more formally regarding tests; will submit a separate PR for them.

**Comment by toonarmycaptain** [comment]
All good. I'll merge this then.
