### ISSUE TITLE
Add installation docs

### ISSUE THREAD

**Issue by schedutron** [toonarmycaptain/dionysus#27]
Currently, there is no documentation to guide local installation and usage of this project. It should be added so that people can install it with ease and other developers can test it conveniently.

@toonarmycaptain Please guide me on how to accomplish this, and add the relevant labels.

**Comment by toonarmycaptain** [comment]
I'm not sure what more there is to say. At the moment downloading and running app-main on a bare Python3 installation 3.6 or later will work. Pytest is needed to run tests. The setup.py is boilerplate to be expanded on later.
