### ISSUE TITLE
Reorganise functions in class_functions.py

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#30]
[class_functions.py](https://github.com/toonarmycaptain/dionysus/blob/switch_to_JSON/dionysus_app/class_functions.py) is getting harder to follow, particularly when [recent additions](https://github.com/toonarmycaptain/dionysus/blob/master/dionysus_app/class_functions.py) from the [move to JSON for class data storage](https://github.com/toonarmycaptain/dionysus/blob/master/dionysus_app/class_functions.py)  #25  get merged into the master branch.

Reorganise the functions so that they're easier to find. eg function definitions found after the function they're first called from, reading from the top of the script, in the order they appear in the calling function. 

Another possibility is factoring some of this script into a seperate script. eg file IO, functions that deal interface with the class registry.

**Comment by Ginkooo** [comment]
I'm on it :)
